### PR TITLE
CI testing, coverage shields, added to packagist and more

### PR DESCRIPTION
**Pull request by LeWestopher**
Added some fancy new stuff:
- CI testing via Travis CI
- Shields showing build success, coverage, and number of downloads
- Added the plugin to Packagist

### CODE REVIEW

**Comment by snelg** [comment]
Nice! That's a big chunk of work for this teeny plugin :)

**Comment by snelg** [comment]
@LeWestopher , please add me as a maintainer of this package on Packagist so that I can add other packages under the vendor name "snelg". My username there is also "snelg".
Thanks!

**Comment by LeWestopher** [comment]
@snelg , just now getting this brother.  Will do immediately.

**Comment by LeWestopher** [comment]
@snelg , it looks like you are already previously a maintainer on Packagist for the package.  I can abandon and allow you to take control, think that would fix the issue?

**Comment by snelg** [comment]
@LeWestopher A Packagist admin added me as a maintainer (at my request) mere minutes before you tried. It's all good now.

**Comment by LeWestopher** [comment]
@snelg , perfect!  sorry about that, glad you got it fixed!

**Pull request merged**
